## http://archive.ics.uci.edu/ml/machine-learning-databases/internet_ads/

In [7]:
import os
import numpy as np
import pandas as pd
ad_path = os.path.join(os.path.pardir,'data','raw','algorithms','supported-vector-machine')
data_path = os.path.join(ad_path,'fromUnivCalifornia')
ad_file_path = os.path.join(data_path,'ad.data')
ad_data = pd.read_csv(ad_file_path,header=None,low_memory=False) 
# yelp_data[yelp_data.isnull().any(axis=1)]
# yelp_data.isnull().any()
ad_data.head(11)

0     1       2    3     4     5     6     7     8     9     ...   1549  \
0    125   125     1.0    1     0     0     0     0     0     0  ...      0   
1     57   468  8.2105    1     0     0     0     0     0     0  ...      0   
2     33   230  6.9696    1     0     0     0     0     0     0  ...      0   
3     60   468     7.8    1     0     0     0     0     0     0  ...      0   
4     60   468     7.8    1     0     0     0     0     0     0  ...      0   
5     60   468     7.8    1     0     0     0     0     0     0  ...      0   
6     59   460  7.7966    1     0     0     0     0     0     0  ...      0   
7     60   234     3.9    1     0     0     0     0     0     0  ...      0   
8     60   468     7.8    1     0     0     0     0     0     0  ...      0   
9     60   468     7.8    1     0     0     0     0     0     0  ...      0   
10     ?     ?       ?    1     0     0     0     0     0     0  ...      0   

    1550  1551  1552  1553  1554  1555  1556  1557  1558  
0      0     0     0     0     0     0     0     0   ad.  
1      0     0     0     0     0     0     0     0   ad.  
2      0     0     0     0     0     0     0     0   ad.  
3      0     0     0     0     0     0     0     0   ad.  
4      0     0     0     0     0     0     0     0   ad.  
5      0     0     0     0     0     0     0     0   ad.  
6      0     0     0     0     0     0     0     0   ad.  
7      0     0     0     0     0     0     0     0   ad.  
8      0     0     0     0     0     0     0     0   ad.  
9      0     0     0     0     0     0     0     0   ad.  
10     0     0     0     0     0     0     0     0   ad.  

[11 rows x 1559 columns]

In [8]:
# check whether a given value is a missing value, if yes, change it to NaN
def toNum(cell):
    try:
        return np.float(cell)
    except:
        return np.nan
def seriesToNum(series):
    return series.apply(toNum)

In [9]:
train_data = ad_data.iloc[0:, 0:-1].apply(seriesToNum)
train_data.head(11)

0      1       2     3     4     5     6     7     8     9     ...   \
0   125.0  125.0  1.0000   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
1    57.0  468.0  8.2105   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
2    33.0  230.0  6.9696   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
3    60.0  468.0  7.8000   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
4    60.0  468.0  7.8000   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
5    60.0  468.0  7.8000   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
6    59.0  460.0  7.7966   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
7    60.0  234.0  3.9000   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
8    60.0  468.0  7.8000   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
9    60.0  468.0  7.8000   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
10    NaN    NaN     NaN   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    

    1548  1549  1550  1551  1552  1553  1554  1555  1556  1557  
0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
7    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
8    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
9    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
10   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[11 rows x 1558 columns]

In [33]:
train_data.dropna(inplace=True)
train_data.head(12)
train_data.iloc[12].values.reshape(1,-1)

array([[90.    , 60.    ,  0.6666, ...,  0.    ,  0.    ,  0.    ]])

In [12]:
def toLabel(str):
    if str == "ad.":
        return 1
    else:
        return 0

In [24]:
train_labels = ad_data.iloc[train_data.index,-1].apply(toLabel)
train_labels.head(11)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
11    1
Name: 1558, dtype: int64

In [25]:
train_labels.count()

2359

In [26]:
# Training Phase
from sklearn.svm import LinearSVC

classifier = LinearSVC()
classifier.fit(train_data[100:2300], train_labels[100:2300])

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [34]:
# Test Phase
classifier.predict(train_data.iloc[12].values.reshape(1,-1))

array([1])

In [35]:
classifier.predict(train_data.iloc[-1].values.reshape(1,-1))

array([0])