In [1]:
# !conda install pytorch torchvision -c pytorch -y
import torch
print(torch.__version__)

1.0.1


In [2]:
# 2-d
tensor_array = torch.Tensor([[1,2],[4,5]])
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [3]:
tensor_uninitialized = torch.Tensor(3,3)

In [4]:
# calculate the total number of elements: shape
torch.numel(tensor_uninitialized)

9

In [5]:
# initialize the tensor directly via torch.rand(allocate memory for valid values)
tensor_initialized = torch.rand(2,3)
tensor_initialized

tensor([[0.7097, 0.0919, 0.4826],
        [0.3086, 0.8073, 0.6670]])

In [17]:
# randn for initializing normal distributed values?
tensor_int = torch.randn(5,3).type(torch.IntTensor)
tensor_int

tensor([[-0.7696,  0.2409,  0.5594],
        [ 2.4042, -0.5529, -0.4529],
        [ 1.1152,  0.8858, -0.0090],
        [-0.1285,  0.1524,  2.1805],
        [ 1.0865,  1.5070,  0.6960]])

In [7]:
# initialize long value tensor
tensor_long = torch.LongTensor([1.0,2.0,3.0])
tensor_long

tensor([1, 2, 3])

In [18]:
# byte: unsigned integer: 0~255
tensor_byte = torch.ByteTensor([0,261,1,-5])
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [9]:
tensor_ones = torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
tensor_zeroes = torch.zeros(10)
tensor_zeroes

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
non_zero = torch.nonzero(tensor_eye) # to find the index of all elements in tensor that are non zero
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [19]:
tensor_ones_shape_eye = torch.ones_like(tensor_eye)
tensor_ones_shape_eye

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
tensor_ones_shape_xyz = torch.ones_like(non_zero)
tensor_ones_shape_xyz

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [14]:
# inplace(modify existing tensor) tensor operation is with _
initial_tensor = torch.rand(3,3)
initial_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [23]:
# out of place operation: give a new tensor, origin not modified
new_tensor = initial_tensor.add(4)
new_tensor

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [24]:
#inplace again
initial_tensor.add_(5)
initial_tensor

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])