In [5]:
# !conda install pytorch torchvision -c pytorch -y
import torch
print(torch.__version__)

0.4.1


In [6]:
tensor_array = torch.Tensor([[1,2],[4,5]])
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [7]:
tensor_uninitialized = torch.Tensor(3,3)

In [8]:
torch.numel(tensor_uninitialized)

9

In [9]:
tensor_initialized = torch.rand(2,3)
tensor_initialized

tensor([[0.7903, 0.4990, 0.2607],
        [0.4666, 0.4668, 0.5202]])

In [10]:
tensor_int = torch.randn(5,3).type(torch.IntTensor)
tensor_int

tensor([[ 0,  0,  1],
        [ 1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0,  1],
        [ 0,  0,  1]], dtype=torch.int32)

In [11]:
tensor_long = torch.LongTensor([1.0,2.0,3.0])
tensor_long

tensor([1, 2, 3])

In [12]:
tensor_byte = torch.ByteTensor([0,261,1,-5])
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [13]:
tensor_ones = torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
tensor_zeroes = torch.zeros(10)
tensor_zeroes

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
non_zero = torch.nonzero(tensor_eye) # to find the index of all elements in tensor that are non zero
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [18]:
tensor_ones_shape_eye = torch.ones_like(tensor_eye)
tensor_ones_shape_eye

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
# inplace tensor operation is with _
initial_tensor = torch.rand(3,3)
initial_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])