In [6]:
# !conda install pytorch torchvision -c pytorch -y
import torch
print(torch.__version__)
print(torch.cuda.is_available())

1.4.0
True


In [2]:
torch.get_default_dtype()

torch.float32

In [3]:
torch.set_default_dtype(torch.int)

TypeError: only floating-point types are supported as the default type

In [4]:
# torch.set_default_dtype(torch.float64)

### A list of all tensor types supported by pytorch:
[official page](https://pytorch.org/docs/stable/tensors.html)

## GPU - Cuda

In [7]:
# init() can be used for initializing CUDA state when interacting with its C API, for python, the CUDA state will be initialized on demand
# torch.cuda.init()

torch.cuda.current_device()

0

In [8]:
torch.cuda.device_count()

1

In [ ]:
torch.cuda.empty_cache() # clear unused memory cache

In [16]:
torch.cuda.memory_allocated() # what's the unit?

512

In [17]:
torch.cuda.memory_cached()

2097152

In [11]:
cuda = torch.device('cuda') # returns current default cuda device
# cudaN = torch.device('cuda:N') # N can be any integer ranging from 0
cuda

device(type='cuda')

In [12]:
x_default = torch.tensor([10., 20.], device=cuda)
x_default

In [13]:
y = x_default.cuda() # cuda() is to copy the object onto cuda memory, if already on cuda memory for default cuda device, no copy exeucted
y # if cuda() is used on the cuda device other than de default cuda one, will copy onto default cuda device memory

tensor([10., 20.], device='cuda:0')

In [14]:
print('Outside with context: ', torch.cuda.current_device())
with torch.cuda.device(0): # change the default cuda device to whichever you want
    print('Inside with context: ', torch.cuda.current_device())
print('Outside with context again: ', torch.cuda.current_device())

Outside with context:  0
Inside with context:  0
Outside with context again:  0


In [15]:
# move(copy) a tensor to another device
# b1 = a0.to(device=cuda1) # to() is used to perform tensor data type or device conversion
# b1

In [18]:
preserve_context_gpu = x_default.new_full([2,2], fill_value=1.1) # new_ will cereate new tensors of the same type on the same device
preserve_context_gpu

tensor([[1.1000, 1.1000],
        [1.1000, 1.1000]], device='cuda:0')

In [19]:
x_default

tensor([10., 20.], device='cuda:0')